// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7lc_iIae0irUYKnaXmEiA42uCv_LikQ',
    appId: '1:386628172973:web:de2af699ebd4954aef1a24',
    messagingSenderId: '386628172973',
    projectId: 'flashcard-soft',
    authDomain: 'flashcard-soft.firebaseapp.com',
    storageBucket: 'flashcard-soft.appspot.com',
    measurementId: 'G-4MW0NR9NHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPeVvU2veIgvUGEgKhoPE9hC2YRJgmlaY',
    appId: '1:386628172973:android:f94a2c33477ac7fdef1a24',
    messagingSenderId: '386628172973',
    projectId: 'flashcard-soft',
    storageBucket: 'flashcard-soft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJpfx-tpJdhtEvNObM_SEGES82NWaGuIs',
    appId: '1:386628172973:ios:9da6f133f5a3caceef1a24',
    messagingSenderId: '386628172973',
    projectId: 'flashcard-soft',
    storageBucket: 'flashcard-soft.appspot.com',
    iosBundleId: 'com.example.flutterFlashcards',
  );
}
